# Generated by Django 3.2.16 on 2024-04-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodNutrientTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdc_id', models.IntegerField()),
                ('nutrient_id', models.IntegerField()),
                ('amount', models.FloatField()),
                ('data_points', models.CharField(blank=True, max_length=255, null=True)),
                ('derivation_id', models.IntegerField()),
                ('min', models.CharField(blank=True, max_length=255, null=True)),
                ('max', models.CharField(blank=True, max_length=255, null=True)),
                ('median', models.CharField(blank=True, max_length=255, null=True)),
                ('loq', models.CharField(blank=True, max_length=255, null=True)),
                ('footnote', models.CharField(blank=True, max_length=255, null=True)),
                ('min_year_acquired', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
