# Generated by Django 3.2.16 on 2024-04-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0002_foodnutrienttable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodnutrienttable',
            name='fdc_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
