# Generated by Django 4.2.7 on 2024-05-08 14:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_api', '0002_image_alter_blog_image_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eaten',
            name='eatenDate',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_nutrition', models.CharField(blank=True, max_length=255, null=True)),
                ('goal_amount', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
