# Generated by Django 3.2.16 on 2024-03-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0002_foodnutrient_foodtable_foundationfood_samplefood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodnutrient',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='foodnutrient',
            name='nutrient_nbr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodnutrient',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodnutrient',
            name='unit_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='foodtable',
            name='food_category_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
