# Generated by Django 4.2.7 on 2024-03-09 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0003_remove_ingredient_recipe_recipe_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='category',
            new_name='categories',
        ),
    ]
