# Generated by Django 3.2.16 on 2024-03-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0004_alter_foodnutrient_nutrient_nbr'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdc_id', models.IntegerField(blank=True, null=True)),
                ('seq_num', models.IntegerField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('portion_description', models.CharField(blank=True, max_length=255, null=True)),
                ('gram_weight', models.FloatField(blank=True, null=True)),
                ('retention_code', models.CharField(blank=True, max_length=255, null=True)),
                ('survey_flag', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
