# Generated by Django 4.2.7 on 2024-04-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0004_blog_serving_blog_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrition',
            name='fiber',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutrition',
            name='sugars',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutrition',
            name='vitamina',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutrition',
            name='vitaminb',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutrition',
            name='vitamind',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
