# Generated by Django 4.2.7 on 2024-04-18 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0002_userbookmark'),
        ('blog_api', '0005_inputfood'),
    ]

    operations = [
    ]
