# Generated by Django 3.2.16 on 2024-04-18 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0002_userbookmark'),
        ('blog_api', '0005_inputfood'),
    ]

    operations = [
    ]
