# Generated by Django 4.2.7 on 2024-04-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0006_merge_0002_userbookmark_0005_inputfood'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cookingtime',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='preparationtime',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='rate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inputfood',
            name='sr_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
