# Generated by Django 3.2.16 on 2024-04-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='diet_goals',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='food_allergies',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
