# Generated by Django 3.2.16 on 2024-04-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0007_inputfood_sr_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtable',
            name='data_type',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='foodtable',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='foodtable',
            name='food_category_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
